### ISSUE TITLE
SelectBuilder methods for LIMIT & OFFSET

### ISSUE THREAD

**Issue by stykiaz** [irenical/drowsy#9]
Instead of having to insert literals when doing pagination it would be handy to have the methods there auto generating the sql.

`SelectBuilder.select().from().where()....limit(X).offset(Y)`

**Comment by dneves** [comment]
problem is, limit / offset are not sql standard. they way to limit/offset is dependent on the db used (sql server, postgresql, etc).

**Comment by tiagosimao** [comment]
Although not being SQL standard, I don't see a major problem in having these methods in the builders. Drowsy builders don't aim at correctness, syntax validation would be an insane endeavour. Very specific constructs should be avoided, but limit/offset seems broad enough (MySQL/PostgreSQL/SQLite/...). Thoughts?

**Comment by gedl** [comment]
Call them "page number" and "page size" and delegate the keywords on the implementations

**Comment by tiagosimao** [comment]
@gedl that would be less readable. I think the best option is to create a MySQL specific module. It's something we already knew would have to happen sooner or later.

**Comment by tiagosimao** [comment]
I've created a module for MySQL query building and added the methods limit and offset
Just add this dependency to your project (should be on maven central in a couple of hours):
```pom
<dependency>
    <groupId>org.irenical.drowsy</groupId>
    <artifactId>drowsy-query-mysql</artifactId>
    <version>0.1.4</version>
</dependency>
```
You can then use MySqlSelectBuilder instead of SelectBuilder (you'll have both).
```java
MySqlSelectBuilder.select("*").from("some_table")
    .where("some_field").eq("some_value")
    .limit(100)
    .offset(10);
```
The non-Postgres compatible syntax is also supported
```java
MySqlSelectBuilder.select("*").from("some_table")
    .where("some_field").eq("some_value")
    .limit(10,100);
```
Will mark as closed, but get back at me if you have some problem using it. Feel free to pull request any other MySql features to this module.
Cheers!
